# Generated by Django 3.1.3 on 2020-11-21 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_account_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='usernames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
